# Generated by Django 5.1.6 on 2025-02-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('stream_url', models.URLField()),
                ('topic', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('is_live', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lectures',
                'ordering': ['-start_time'],
            },
        ),
    ]
