# Generated by Django 5.1.6 on 2025-03-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='location',
        ),
        migrations.AddField(
            model_name='lecture',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
